<?php

/**
 * @file
 * Islandora Demo stuff.
 */

/**
 * Implements hook_rdf_namespaces().
 */
function islandora_demo_rdf_namespaces() {
  return [
    'relators' => 'http://id.loc.gov/vocabulary/relators/',
  ];
}

/**
 * Implements hook_preprocess_views_view_unformatted().
 *
 * Modifies the peers_block view results to set a 'active-peer'
 * CSS class on the row that matches the currently displayed node.
 * Either add the CSS to your theme or, if using adaptive_theme,
 * optionally add it to the Custom CSS extension.
 */
function islandora_demo_preprocess_views_view_unformatted(&$vars) {
  $view = $vars['view'];
  if ($vars['view']->current_display == 'peers_block') {
    $path = \Drupal::service('path.alias_manager')
      ->getAliasByPath(\Drupal::service('path.current')
        ->getPath());
    foreach ($vars['rows'] as $id => $row) {
      $entity = $row['content']['#row']->_entity;
      $media_of = $entity->field_media_of->entity->toUrl()->toString();
      if ($path == $media_of) {
        $vars['rows'][$id]['attributes']->addClass('active-peer');
      }
    }
  }
}
